
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Usuario
 */
public class Planetas extends javax.swing.JFrame {
 public static int nplaneta;
    /**
     * Creates new form Planetas
     * hacemos una funcion cargarplanetaincial que muestre los datos del planeta 8 nada mas cargar la base de datos
     */
    public Planetas() {
        initComponents();
        cargarPlanetaInicial();
    }
    public void cargarPlanetaInicial(){//funcion de precargar de datos 
        if(nplaneta == 0){
            nplaneta = 8;
        }
        String imagePath = "";
        String nombrePlaneta = ""; // Variable para almacenar el nombre del planeta
        double radioPlaneta = 0;
        double Distancia_sol = 0;
        double Periodo_orbita = 0;
        int Temperatura = 0;
        String Tipo_planeta = "";
        int Numero_satelites = 0;
        String Fecha_creacion = "";
        try {
            nombrePlaneta = Conectorbd.getNombrePlaneta(nplaneta); // Obtener el nombre del planeta desde la base de datos
            radioPlaneta = Conectorbd.getRadioPlaneta(nplaneta);
            Distancia_sol = Conectorbd.getdistancia_solPlaneta(nplaneta);
            Periodo_orbita = Conectorbd.getperiodo_orbitaPlaneta(nplaneta);
            Temperatura = Conectorbd.getTemperaturaPlaneta(nplaneta);
            Tipo_planeta = Conectorbd.gettipo_planeta(nplaneta);
            Numero_satelites = Conectorbd.getnumero_satelites(nplaneta);
            Fecha_creacion = Conectorbd.getfecha_creacion(nplaneta);
        } catch (SQLException ex) {
            ex.printStackTrace();
            // Aquí puedes manejar el error de alguna manera, por ejemplo, mostrando un mensaje de error al usuario
        }
        nombreplaneta.setText(nombrePlaneta);
        radioplaneta.setText(String.valueOf(radioPlaneta));
        distancia_sol.setText(String.valueOf(Distancia_sol));
        periodo_orbita.setText(String.valueOf(Periodo_orbita));
        temperatura.setText(String.valueOf(Temperatura));
        tipo_planeta.setText(String.valueOf(Tipo_planeta));
        numero_satelites.setText(String.valueOf(Numero_satelites));
        fecha_creacion.setText(String.valueOf(Fecha_creacion));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selector = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Estrellas = new javax.swing.JButton();
        Lunas = new javax.swing.JButton();
        planetaimg = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        nombreplaneta = new javax.swing.JLabel();
        radioplaneta = new javax.swing.JLabel();
        distancia_sol = new javax.swing.JLabel();
        periodo_orbita = new javax.swing.JLabel();
        temperatura = new javax.swing.JLabel();
        tipo_planeta = new javax.swing.JLabel();
        numero_satelites = new javax.swing.JLabel();
        fecha_creacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selector.setMaximum(8);
        selector.setMinimum(1);
        selector.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                selectorStateChanged(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercurioico.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tierraico.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jupiterico.jpg"))); // NOI18N
        jLabel3.setText("jLabel2");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/venusico.jpg"))); // NOI18N
        jLabel4.setText("jLabel2");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saturnoico.jpg"))); // NOI18N
        jLabel5.setText("jLabel2");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marteico.jpg"))); // NOI18N
        jLabel6.setText("jLabel2");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptunoico.jpg"))); // NOI18N
        jLabel7.setText("jLabel2");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uranoico.jpg"))); // NOI18N
        jLabel8.setText("jLabel2");

        Estrellas.setText("Estrellas");
        Estrellas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstrellasActionPerformed(evt);
            }
        });

        Lunas.setText("Satelites");
        Lunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LunasActionPerformed(evt);
            }
        });

        planetaimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno.jpg"))); // NOI18N
        planetaimg.setText("planeta");
        planetaimg.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                planetaimgComponentAdded(evt);
            }
        });

        jLabel9.setText("Radio");

        jLabel10.setText("Distancia media al sol");

        jLabel11.setText("Periodo orbital");

        jLabel12.setText("Temperatura media");

        jLabel13.setText("Tipo de planeta");

        jLabel15.setText("fecha creacion");

        jLabel17.setText("nombre");

        nombreplaneta.setText("jLabel18");

        radioplaneta.setText("jLabel18");

        distancia_sol.setText("jLabel18");

        periodo_orbita.setText("jLabel18");

        temperatura.setText("jLabel18");

        tipo_planeta.setText("jLabel18");

        numero_satelites.setText("jLabel18");

        fecha_creacion.setText("jLabel18");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Estrellas)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 8, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(107, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(selector, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 132, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(planetaimg, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(Lunas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreplaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioplaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(temperatura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                .addComponent(periodo_orbita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(numero_satelites, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fecha_creacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tipo_planeta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(distancia_sol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(planetaimg, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel16)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(nombreplaneta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(radioplaneta))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(distancia_sol))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(periodo_orbita))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(temperatura))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tipo_planeta))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numero_satelites)
                            .addComponent(Lunas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(fecha_creacion))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Estrellas)
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void EstrellasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstrellasActionPerformed
        main mainframe = new main();
        mainframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_EstrellasActionPerformed

    private void planetaimgComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_planetaimgComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_planetaimgComponentAdded

    private void selectorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_selectorStateChanged //Aqui recogeremos los valores de los datos en el programa segun el sidebar
       
        
        nplaneta = selector.getValue();
            
        
        String imagePath = "";
        String nombrePlaneta = ""; 
        double radioPlaneta = 0;
        double Distancia_sol = 0;
        double Periodo_orbita = 0;
        int Temperatura = 0;
        String Tipo_planeta = "";
        int Numero_satelites = 0;
        String Fecha_creacion = "";
        
       
        
            try {
            nombrePlaneta = Conectorbd.getNombrePlaneta(nplaneta); // Obtener el nombre del planeta desde la base de datos
            radioPlaneta = Conectorbd.getRadioPlaneta(nplaneta);
            Distancia_sol = Conectorbd.getdistancia_solPlaneta(nplaneta);
            Periodo_orbita = Conectorbd.getperiodo_orbitaPlaneta(nplaneta);
            Temperatura = Conectorbd.getTemperaturaPlaneta(nplaneta);
            Tipo_planeta = Conectorbd.gettipo_planeta(nplaneta);
            Numero_satelites = Conectorbd.getnumero_satelites(nplaneta);
            Fecha_creacion = Conectorbd.getfecha_creacion(nplaneta);
        } catch (SQLException ex) {
            ex.printStackTrace();
            // Aquí puedes manejar el error de alguna manera, por ejemplo, mostrando un mensaje de error al usuario
        }
        
        
        
        nombreplaneta.setText(nombrePlaneta);
        radioplaneta.setText(String.valueOf(radioPlaneta));
        distancia_sol.setText(String.valueOf(Distancia_sol));
        periodo_orbita.setText(String.valueOf(Periodo_orbita));
        temperatura.setText(String.valueOf(Temperatura));
        tipo_planeta.setText(String.valueOf(Tipo_planeta));
        numero_satelites.setText(String.valueOf(Numero_satelites));
        fecha_creacion.setText(String.valueOf(Fecha_creacion));
        switch (nplaneta) {
            case 1:
                imagePath = "/mercurio.jpg";

                break;
            case 2:
                imagePath = "/venus.jpg";
                break;
            case 3:
                imagePath = "/tierra.jpg";
                break;
            case 4:
                imagePath = "/marte.jpg";
                break;
            case 5:
                imagePath = "/jupiter.jpg";
                break;
            case 6:
                imagePath = "/saturno.jpg";
                break;
            case 7:
                imagePath = "/urano.jpg";
                break;
            case 8:
                imagePath = "/neptuno.jpg";
                break;
        }
        if (!imagePath.isEmpty()) {
            ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
            planetaimg.setIcon(icon);
        }

    }//GEN-LAST:event_selectorStateChanged

    private void LunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LunasActionPerformed

       int Numero_satelites = 0;
        try {
            Numero_satelites = Conectorbd.getnumero_satelites(nplaneta);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        if(Numero_satelites < 1){
             JOptionPane.showMessageDialog(null, "Este Planeta no Tiene ningun Satelite registrado");
        }
        else{
            Satelites Satelitesframe = new Satelites();
            Satelitesframe.setVisible(true); 
            dispose();
        }
        
       
           
        
        
        
       
        
        
    }//GEN-LAST:event_LunasActionPerformed

    /**
     * @param args the command line arguments
     */
   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planetas().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Estrellas;
    private javax.swing.JButton Lunas;
    private javax.swing.JLabel distancia_sol;
    private javax.swing.JLabel fecha_creacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nombreplaneta;
    private javax.swing.JLabel numero_satelites;
    private javax.swing.JLabel periodo_orbita;
    private javax.swing.JLabel planetaimg;
    private javax.swing.JLabel radioplaneta;
    private javax.swing.JSlider selector;
    private javax.swing.JLabel temperatura;
    private javax.swing.JLabel tipo_planeta;
    // End of variables declaration//GEN-END:variables
}
