
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.Query.value;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Usuario
 */
public class Satelites extends javax.swing.JFrame {

    /**
     * Creates new form Satelites
     * precargamos otra vez los datos
     */
    public Satelites() {
        initComponents();
        cargarSatelites();
    }
    public void cargarSatelites(){
        String nsatelite = (String) jComboBox1.getSelectedItem();
        if(nsatelite == null){
           
        }
        String imagePath = "";
        String planetasatelite = "";
        double Sateliteradio = 0;
        double Satelitedistancia = 0;
        double Sateliteperiodo = 0;
        int Satelitetemperatura = 0;
        String Satelitetipo = "";
        String Satelitefechacreacion = "";
        int id = 0;
        try {
            planetasatelite = Conectorbd.getPlanetaSatelite(nsatelite);
            Sateliteradio = Conectorbd.getsateliteradio(nsatelite);
            Satelitedistancia = Conectorbd.getSateliteDistanciaPlaneta(nsatelite);
            Sateliteperiodo = Conectorbd.getSatelitePeriodoOrbital(nsatelite);
            Satelitetemperatura = Conectorbd.getSateliteTemperatura(nsatelite);
            Satelitetipo = Conectorbd.getSateliteTipo(nsatelite);
            Satelitefechacreacion = Conectorbd.getSateliteFechaCreacion(nsatelite);
            id = Conectorbd.getsateliteid(nsatelite);

        } catch (SQLException ex) {
            Logger.getLogger(Satelites.class.getName()).log(Level.SEVERE, null, ex);
        }
        nombreplaneta.setText(planetasatelite);
        sateliteradio.setText(String.valueOf(Sateliteradio));
        satelitedistancia.setText(String.valueOf(Satelitedistancia));
        sateliteperiodo.setText(String.valueOf(Sateliteperiodo));
        satelitetemperatura.setText(String.valueOf(Satelitetemperatura));
        satelitetipo.setText(String.valueOf(Satelitetipo));
        satelitefechacreacion.setText(String.valueOf(Satelitefechacreacion));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        sateliteimg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreplaneta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sateliteradio = new javax.swing.JLabel();
        satelitedistancia = new javax.swing.JLabel();
        sateliteperiodo = new javax.swing.JLabel();
        satelitetemperatura = new javax.swing.JLabel();
        satelitetipo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        satelitefechacreacion = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cargar Satelites");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        sateliteimg.setText("‎ ");

        jLabel2.setText("Planeta");

        nombreplaneta.setText("jLabel3");

        jLabel3.setText("Radio");

        jLabel4.setText("Distancia");

        jLabel5.setText("Periodo ");

        jLabel6.setText("Temperatura");

        jLabel7.setText("tipo");

        sateliteradio.setText("jLabel8");

        satelitedistancia.setText("jLabel8");

        sateliteperiodo.setText("jLabel8");

        satelitetemperatura.setText("jLabel8");

        satelitetipo.setText("jLabel8");

        jLabel8.setText("fecha");

        satelitefechacreacion.setText("jLabel9");

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Volver)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sateliteimg, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombreplaneta, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(satelitedistancia, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(sateliteradio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(satelitefechacreacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(satelitetipo, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(satelitetemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sateliteperiodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(nombreplaneta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(sateliteradio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(satelitedistancia))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(sateliteperiodo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(satelitetemperatura))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(satelitetipo))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(satelitefechacreacion))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Volver)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sateliteimg, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(84, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
// Borra todos los elementos existentes en el comboBox
        jComboBox1.removeAllItems();
        Planetas idplaneta = new Planetas();

// Obtener el nombre del planeta seleccionado desde Planeta
        String[] arrPlanetas = {"Mercurio", "Venus", "Tierra", "Marte", "Júpiter", "Saturno", "Urano", "Neptuno"};
        String nombrePlaneta = arrPlanetas[idplaneta.nplaneta - 1];
        System.out.println(idplaneta.nplaneta);

// Obtener los satélites del planeta seleccionado y agregarlos al comboBox
        try {

            String[] satelites = Conectorbd.getSatelitesPorPlaneta(nombrePlaneta);
            for (int i = 0; i < satelites.length; i++) {
                jComboBox1.addItem(satelites[i]);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed // cargamos los datos de la base al programa 
        String nsatelite = (String) jComboBox1.getSelectedItem();
        String imagePath = "";
        String planetasatelite = "";
        double Sateliteradio = 0;
        double Satelitedistancia = 0;
        double Sateliteperiodo = 0;
        int Satelitetemperatura = 0;
        String Satelitetipo = "";
        String Satelitefechacreacion = "";
        int id = 0;
        try {
            planetasatelite = Conectorbd.getPlanetaSatelite(nsatelite);
            Sateliteradio = Conectorbd.getsateliteradio(nsatelite);
            Satelitedistancia = Conectorbd.getSateliteDistanciaPlaneta(nsatelite);
            Sateliteperiodo = Conectorbd.getSatelitePeriodoOrbital(nsatelite);
            Satelitetemperatura = Conectorbd.getSateliteTemperatura(nsatelite);
            Satelitetipo = Conectorbd.getSateliteTipo(nsatelite);
            Satelitefechacreacion = Conectorbd.getSateliteFechaCreacion(nsatelite);
            id = Conectorbd.getsateliteid(nsatelite);

        } catch (SQLException ex) {
            Logger.getLogger(Satelites.class.getName()).log(Level.SEVERE, null, ex);
        }
        nombreplaneta.setText(planetasatelite);
        sateliteradio.setText(String.valueOf(Sateliteradio));
        satelitedistancia.setText(String.valueOf(Satelitedistancia));
        sateliteperiodo.setText(String.valueOf(Sateliteperiodo));
        satelitetemperatura.setText(String.valueOf(Satelitetemperatura));
        satelitetipo.setText(String.valueOf(Satelitetipo));
        satelitefechacreacion.setText(String.valueOf(Satelitefechacreacion));
        switch (id) {
            case 1:
                imagePath = "/luna.gif";
                break;
            case 2:
                imagePath = "/fobos.jpg";
                break;
            case 3:
                imagePath = "/deimos.jpg";
                break;
            case 4:
                imagePath = "/io.jpg";
                break;
            case 5:
                imagePath = "/europa.jpg";
                break;
            case 6:
                imagePath = "/gaminides.jpg";
                break;
            case 7:
                imagePath = "/callisto.jpg";
                break;
            case 8:
                imagePath = "/titan.jpg";
                break;
            case 9:
                imagePath = "/encelado.jpg";
                break;
            case 10:
                imagePath = "/titania.jpg";
                break;
            case 11:
                imagePath = "/oberon.jpg";
                break;
        }
        if (!imagePath.isEmpty()) {
            ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
            sateliteimg.setIcon(icon);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        Planetas planetaframe = new Planetas();
        planetaframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Satelites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Satelites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Satelites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Satelites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Satelites().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel nombreplaneta;
    private javax.swing.JLabel satelitedistancia;
    private javax.swing.JLabel satelitefechacreacion;
    private javax.swing.JLabel sateliteimg;
    private javax.swing.JLabel sateliteperiodo;
    private javax.swing.JLabel sateliteradio;
    private javax.swing.JLabel satelitetemperatura;
    private javax.swing.JLabel satelitetipo;
    // End of variables declaration//GEN-END:variables
}
